In [1]:
strArr = "X:-1", "Y:1", "X:-4", "B:3", "X:5"

In [2]:

    dict = {}
    
    for item in strArr:
        key,value = item.split(":")
        
        if key in dict:
            dict[key] += int(value)
            
        else:
            dict[key] = int(value)

In [5]:
dict.items()

dict_items([('X', 0), ('Y', 1), ('B', 3)])

In [6]:
sorted_dict = dict.items()
sorted_dict = sorted(sorted_dict)

In [8]:
type(sorted_dict)

list

In [10]:
final = ""
for key, value in sorted_dict:
    if value!= 0:
        final += key + ":" + str(value) + ","
        
final = final[:-1]

print(final)

B:3,Y:1


In [1]:
def BasicRomanNumerals(strParam):

  # code goes here

  roman_numerals = {'I': 1, 'V': 5, 'X': 10, 'L': 50, 'C':100, 'D':500, 'M': 1000}
  numbers = 0

  for i in range(len(strParam)):
    value = roman_numerals[strParam[i]]
    
    if (i+1)< len(strParam) and roman_numerals[strParam[i+1]] > value:
      numbers = numbers - value

    else:
      numbers = numbers + value
  
  return numbers

In [2]:
def GroupTotals(arr):

  # code goes here
  dict = {}
    
  for item in arr:
    key,value = item.split(":")
        
    if key in dict:
      dict[key] += int(value)
            
    else:
      dict[key] = int(value)

  sorted_dict = dict.items()
  sorted_dict = sorted(sorted_dict)

  temp = ""
  for key, value in sorted_dict:
    if value!= 0:
      temp += key + ":" + str(value) + ","

  temp = temp[:-1]
  
  return temp

In [5]:
arr = [2,1,3,4,1]
for i in range(len(arr)):
    print(arr[i])

2
1
3
4
1


In [7]:
import numpy as np
area = np.array([])

In [8]:
area

array([], dtype=float64)

In [9]:
arr = [2,1,3,4,1]

In [18]:
arr= [6,3,1,4,12,4]

In [21]:
area = np.array([])

i = 0
max_area = 0

for i in range(len(arr)-1):
    if (arr[i] < arr[i+1]):
        ar = arr[i]*2
        area = np.append(area, ar)
        
max_area = area.max()

In [22]:
max_area

8.0

In [26]:
area = np.array([])

i = 0
max_area = 0

for i in range(len(arr)-1):
    if (arr[i] < arr[i+1]):
        if(arr[i] <= arr[i+2]):
            ar2 = arr[i]*3
            area = np.append(area,ar2)
            
        ar = arr[i]*2
        area = np.append(area, ar)
        
max_area = area.max()

In [27]:
max_area

15.0

In [25]:
arr= [5,6,7,4,1]

### Q5: Queen Check

In [86]:
strArr = ["(3,1)","(4,4)"]

In [87]:
strArr = np.array(strArr)

In [88]:
strArr

array(['(3,1)', '(4,4)'], dtype='<U5')

In [89]:
strArr[0][3]

'1'

In [90]:
queen = {'x1': strArr[0][1], 'y1': strArr[0][3]}
king = {'x2': strArr[1][1], 'y2': strArr[1][3]}

In [91]:
if (king['x2'] == queen['x1'] and king['y2'] == queen['y1']):
    print('Queen is captured, NOT IN CHECK')
    
elif (np.abs(int(king['x2'])- int(queen['x1'])) == 1) or (np.abs(int(king['y2'])- int(queen['y1'])) == 1):
    print('-1')
    print('King is IN CHECK')
    
else:
    print(max(np.abs(int(king['x2'])- int(queen['x1'])), np.abs(int(king['y2'])- int(queen['y1']))))
    

-1
King is IN CHECK


## Q6: 'Knight jumps'

In [116]:
strParam = "(4 5)"

In [117]:
x,y = int(strParam[1]),int(strParam[3])

In [119]:
comparisons = ["x+2 <= 8", "x-2 >= 0", "y+2 <= 8", "y-2 >= 0"]

In [120]:
results= []

for i in range(len(comparisons)):
    results.append(eval(comparisons[i]))

In [121]:
results

[True, True, True, True]

In [122]:
np.count_nonzero(results)

4

### Q2: Food distribution

In [13]:
import numpy as np
arr = [5,3,1,2,1]

In [20]:
num_sandwiches = arr[0]
difference = 0
arr_diff= []

In [21]:
for i in range(1,len(arr)-1):
    temp = np.abs(arr[i] - arr[i+1])
    difference = difference + temp
    arr_diff = np.append(arr_diff, temp)          

In [23]:
sum(arr_diff)

4.0

In [ ]:
for i in range(len(arr)-1):
    combos = []
    

## Assignment 2:

#### Q1: Permutation Step

In [31]:
num= 123
num = str(num)

In [25]:
perm_list = []

In [35]:
import itertools
perm = list(itertools.permutations(num))

In [38]:
type(perm[0])

tuple

In [39]:
res= [''.join(tups) for tups in perm]

In [40]:
res

['123', '132', '213', '231', '312', '321']

In [45]:
res2 = [eval(i) for i in res]
res2

[123, 132, 213, 231, 312, 321]

In [51]:
res2.sort()
print(res2)

[123, 132, 213, 231, 312, 321]


In [55]:
for i in range(len(res2)):
    if res2[i] > int(num):
        break
    else:
        continue
        
num = res2[i]

In [56]:
num

132

### Q3: Reverse a string

In [70]:
s = 'My name is Govind'

In [71]:
s = 'Govind is my name'
s = s[::-1]
print(s)

eman ym si dnivoG


### Q4: Swap Case

In [73]:
s = 'My name is Govind'
s.swapcase()

'mY NAME IS gOVIND'

### Q5: Charlie the Dog

In [178]:
arr = ["FOOF", "OCOO", "OOOH", "FOOO"]

In [179]:
arr2 = []
for i in range(len(arr)):
    arr2.append(arr[i].split(" "))
    

In [180]:
arr2

[['FOOF'], ['OCOO'], ['OOOH'], ['FOOO']]

In [152]:
arr = np.array(list(arr))
arr

array(['FOOF', 'OCOO', 'OOOH', 'FOOO'], dtype='<U4')

In [181]:
arr2 = np.expand_dims(arr2, axis = 1)

In [182]:
arr2

array([[['FOOF']],

       [['OCOO']],

       [['OOOH']],

       [['FOOO']]], dtype='<U4')

In [135]:
arr2 = np.array([[]])
for i in range(len(arr)):
    arr2 = np.append(arr2, arr[i], axis = 0)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 0 dimension(s)

In [145]:
arr3 = np.array([[]])

In [147]:
arr3.reshape(4,4)

ValueError: cannot reshape array of size 0 into shape (4,4)

In [138]:
arr3 = np.append(arr3, arr[i], axis = 0)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 0 dimension(s)

************

In [136]:
import numpy as np

In [137]:
arr = ["FOOF", "OCOO", "OOOH", "FOOO"]

In [66]:
arr2 = []
for i in range(len(arr)):
    arr2.append(arr[i].split(" "))

In [67]:
arr2

[['FOOF'], ['OCOO'], ['OOOH'], ['FOOO']]

In [8]:
a1 = arr[0]

In [68]:
list(arr[0])

['F', 'O', 'O', 'F']

In [19]:
# result = np.concatenate((np.array(list(arr[0])), np.array(list(arr[1])), np.array(list(arr[2])), np.array(list(arr[3]))), axis= 0)
# print(result)

['F' 'O' 'O' 'F' 'O' 'C' 'O' 'O' 'O' 'O' 'O' 'H' 'F' 'O' 'O' 'O']


In [138]:
a1 = np.array(list(arr[0])).reshape((1,4))
a2 = np.array(list(arr[1])).reshape((1,4))
a3 = np.array(list(arr[2])).reshape((1,4))
a4 = np.array(list(arr[3])).reshape((1,4))

In [139]:
result = np.concatenate((a1,a2,a3,a4),axis = 0)
result

array([['F', 'O', 'O', 'F'],
       ['O', 'C', 'O', 'O'],
       ['O', 'O', 'O', 'H'],
       ['F', 'O', 'O', 'O']], dtype='<U1')

In [140]:
food_ar = []

for i in range(4):
    for j in range(4):
        if (result[i][j] == 'H'):
            home_x = i
            home_y = j
            
        elif (result[i][j] == 'C'):
            dog_x = i
            dog_y = j
            
        elif (result[i][j] == 'F'):
            food_x = i
            food_y = j
            food_ar.append([food_x,food_y])

In [221]:
home_x, home_y

(2, 3)

In [142]:
dog_x, dog_y

(1, 1)

In [210]:
food_ar

[[0, 0], [0, 3], [3, 0]]

In [315]:
import itertools
perm = list(itertools.permutations(food_ar))

In [316]:
perm

[([0, 0], [0, 3], [3, 0]),
 ([0, 0], [3, 0], [0, 3]),
 ([0, 3], [0, 0], [3, 0]),
 ([0, 3], [3, 0], [0, 0]),
 ([3, 0], [0, 0], [0, 3]),
 ([3, 0], [0, 3], [0, 0])]

In [317]:
(np.array(perm))

array([[[0, 0],
        [0, 3],
        [3, 0]],

       [[0, 0],
        [3, 0],
        [0, 3]],

       [[0, 3],
        [0, 0],
        [3, 0]],

       [[0, 3],
        [3, 0],
        [0, 0]],

       [[3, 0],
        [0, 0],
        [0, 3]],

       [[3, 0],
        [0, 3],
        [0, 0]]])

In [318]:
perm = np.insert(perm, 0,[dog_x, dog_y], axis= 1)
perm

array([[[1, 1],
        [0, 0],
        [0, 3],
        [3, 0]],

       [[1, 1],
        [0, 0],
        [3, 0],
        [0, 3]],

       [[1, 1],
        [0, 3],
        [0, 0],
        [3, 0]],

       [[1, 1],
        [0, 3],
        [3, 0],
        [0, 0]],

       [[1, 1],
        [3, 0],
        [0, 0],
        [0, 3]],

       [[1, 1],
        [3, 0],
        [0, 3],
        [0, 0]]])

In [319]:
perm = np.insert(perm, 4, [home_x, home_y], axis= 1)
perm

array([[[1, 1],
        [0, 0],
        [0, 3],
        [3, 0],
        [2, 3]],

       [[1, 1],
        [0, 0],
        [3, 0],
        [0, 3],
        [2, 3]],

       [[1, 1],
        [0, 3],
        [0, 0],
        [3, 0],
        [2, 3]],

       [[1, 1],
        [0, 3],
        [3, 0],
        [0, 0],
        [2, 3]],

       [[1, 1],
        [3, 0],
        [0, 0],
        [0, 3],
        [2, 3]],

       [[1, 1],
        [3, 0],
        [0, 3],
        [0, 0],
        [2, 3]]])

In [320]:
perm.shape

(6, 5, 2)

In [329]:
d = []
a = 0

for i in range(perm.shape[0]):
    for j in range((perm.shape[1])-1):
        a += np.abs(perm[i][j][0] - perm[i][j+1][0]) + np.abs(perm[i][j][1] - perm[i][j+1][1])
        
    d.append(a)
    a = 0
print(d)

[15, 13, 13, 17, 11, 17]


### Q5: Plus Minus

In [167]:
num = 26712

In [113]:
# num_str = str(num)
# num_str

'26712'

In [168]:
arr = [int(x) for x in str(num)]
arr

[2, 6, 7, 1, 2]

In [119]:
def recursiveFunc(updated_array, updated_sum):
    if (len(updated_array)==1):
        if (updated_sum + updated_array[0] == 0):
            return '+'
        
        elif (updated_sum - updated_array[0] == 0):
            return '-'
        else:
            return 'not possible'
        
    num_str1 = recursiveFunc(updated_array[1:], updated_sum + updated_array[0])
    
    if (num_str1 != 'not possible'):
        return '+' + num_str1
    
    num_str2 = recursiveFunc(updated_array[1:], updated_sum - updated_array[0])
    
    if (num_str2 != 'not possible'):
        return '-' + num_str2
    
    
    
    return 'not possible'

In [169]:
if len(arr) < 2:
    print('not possible')
    
else:
    print(recursiveFunc(arr[1:], arr[0]))

-+--


### Q2: Longest Increasing Sequence

In [127]:
arr = [4,3,5,1,6]
N = len(arr)
dp = [1]*N

In [135]:
for n in range(len(arr)):
    for i in range(n):
        if arr[i] < arr[n]:
            dp[n] = max(dp[n],dp[i]+1)
print((dp))

[1, 1, 2, 1, 3]


In [132]:
max(dp)

3

In [1]:
def BasicRomanNumerals(strParam):

  # code goes here

  roman_numerals = {'I': 1, 'V': 5, 'X': 10, 'L': 50, 'C':100, 'D':500, 'M': 1000}
  numbers = 0

  for i in range(len(strParam)):
    value = roman_numerals[strParam[i]]
    
    if (i+1)< len(strParam) and roman_numerals[strParam[i+1]] > value:
      numbers = numbers - value

    else:
      numbers = numbers + value
  
  return numbers

In [3]:
print(BasicRomanNumerals("XXXVVIIIIIIIIII"))

50


In [27]:
def num_to_roman(num):
   res = ""
   table = [
      (1000, "M"),
      (900, "CM"),
      (500, "D"),
      (400, "CD"),
      (100, "C"),
      (90, "XC"),
      (50, "L"),
      (40, "XL"),
      (10, "X"),
      (9, "IX"),
      (5, "V"),
      (4, "IV"),
      (1, "I"),
   ]

   for cap, roman in table:
      q, r = divmod(num, cap)
      res += roman * q
      num = r

   return res

num = 1520
print(solve(num))

MDXX


In [21]:
def int_to_roman(number):
    
    roman = [
    (1000, "M"),
    ( 900, "CM"),
    ( 500, "D"),
    ( 400, "CD"),
    ( 100, "C"),
    (  90, "XC"),
    (  50, "L"),
    (  40, "XL"),
    (  10, "X"),
    (   9, "IX"),
    (   5, "V"),
    (   4, "IV"),
    (   1, "I"),
]
    
    result = []
    for (arabic, roman) in dict(roman):
        (factor, number) = divmod(number, arabic)
        result.append(roman * factor)
        if number == 0:
            break
    return "".join(result)

In [17]:
r = dict(roman)

In [22]:
int_to_roman(49)

TypeError: cannot unpack non-iterable int object